### ISSUE TITLE
Drag canvas out of svg area

### ISSUE THREAD

**Issue by mauroIstat** [joyceworks/flowchart-vue#11]
Canvas (start, end, operation) can be dragged out of the svg area. 
**To Reproduce**
1. Go to https://joyceworks.github.io/flowchart-vue/
2. Click on Start
3. Drag Start out of the svg area
4. Start is 'lost'

**Expected behavior**
svg area should have boundaries (therefore canvas cannot exit svg area) or svg area should be scrollable
![flowchart-boundaries](https://user-images.githubusercontent.com/22342712/96928714-48557f00-14b9-11eb-99fb-a9dd499d5c87.png)

**Comment by iamppz** [comment]
Pushed [codes](https://github.com/joyceworks/flowchart-vue/commit/b14ca12d0359ac0601fe97627cd99890965cea41) to prevent nodes out of svg area on the left/top side.
Use [Ctrl + Mouse Wheel] to zoom svg area to display the nodes which are out of svg area on the right/bottom side.

**Comment by mauroIstat** [comment]
Awesome!

Thank you very much :)
