### ISSUE TITLE
How can I block reverse arrow?

### ISSUE THREAD

**Issue by suhakopan** [joyceworks/flowchart-vue#17]
Hello, @iamppz,

I want the to user can't draw a reverse arrow. How can I prevent this?

![image](https://user-images.githubusercontent.com/34922338/107323791-f2ccce80-6ab7-11eb-8502-5f2512da5b71.png)

Also, how can I force use start and end to the? And the user shouldn't multiple connections to one node, how can I prevent this too?

I would be very happy if you can explain how I can make these requests.

Thanks.

**Comment by iamppz** [comment]
Hi, please upgrade to v0.16.1 and try this:
``` vue
<Flowchart @connect="handleConnect" />
```
``` javascript
handleConnect(connection, nodes, connections) {
  // block reverse connection
  if (connections.find(item => item.source.id === connection.destination.id && item.destination.id === connection.source.id)) {
    this.$refs.chart.removeConnection(connection);
  }
  // for multi-connections
  if (connections.find(item => item.destination.id === connection.destination.id)) {
    this.$refs.chart.removeConnection(connection);
  }
},
```

**Comment by iamppz** [comment]
Currently not supported to force use start and end nodes, I'll deal it tomorrow :)

**Comment by suhakopan** [comment]
Hi,

I try code, now I can't create a new connection :) Does not allow any connections. It also deleting another connection when doing reverse connection.

![image](https://user-images.githubusercontent.com/34922338/107471401-2540ff00-6b7e-11eb-9a1b-a32d20731880.png)

I captured a gif to prove: https://gifyu.com/image/Vheu

For force start and stop; Maybe I can check if there are a start and end and connected.

Thank you.

**Comment by iamppz** [comment]
> Hi,
> 
> I try code, now I can't create a new connection :) Does not allow any connections. It also deleting another connection when doing reverse connection.
> 
> ![image](https://user-images.githubusercontent.com/34922338/107471401-2540ff00-6b7e-11eb-9a1b-a32d20731880.png)
> 
> I captured a gif to prove: https://giphy.com/gifs/BOKO57GqUmnNoCuaEn
> 
> For force start and stop; Maybe I can check if there are a start and end and connected.
> 
> Thank you.

"THE OWNER HAS SET THIS GIF TO PRIVATE."

**Comment by suhakopan** [comment]
I changed URL, sorry
https://gifyu.com/image/Vheu

**Comment by iamppz** [comment]
Sorry, I found the problem, try this:
```javascript
handleConnect(connection, nodes, connections) {
  // block reverse connection
  if (connections.find(item => item.source.id === connection.destination.id && item.destination.id === connection.source.id)) {
    this.$refs.chart.removeConnection(connection);
    return;  // should return after remove
  }
  // for multi-connections
  if (connections.find(item => item.destination.id === connection.destination.id 
      && item.id !== connection.id)) {  // exclude itself
    this.$refs.chart.removeConnection(connection);
  }
},
```

**Comment by suhakopan** [comment]
Thank you so much for everything, You are great. It's work. I hope I can force the start and end nodes to the user.

**Comment by suhakopan** [comment]
Hello, again @iamppz,
I guess the reverse connection problem continues. This may not be done just by looking at the connections. I think it will also be necessary to look at the x and y coordinates of the nodes. I was able to force the Start and End nodes to the user.

![image](https://user-images.githubusercontent.com/34922338/107546279-408f2700-6bdd-11eb-8b95-5ef56758ac0d.png)

**Comment by iamppz** [comment]
😭Can you provide a gif or some codes to represent it?

**Comment by iamppz** [comment]
It's Chinese New Year today, so I may not reply soon in the next days.

**Comment by suhakopan** [comment]
Happy new year. 

These are reverse connection examples.

First example; https://gifyu.com/image/Vle6
Second example; https://gifyu.com/image/VleZ (In this example, I want to show create a connection to the start node)

------

Can I ask a question on another topic? I want to drag and drop to add new nodes. Can this be done by creating a new chart and using only operation nodes? Or should I use a different component? To add nodes from one chart to another, I have to use the drag-drop feature.

![image](https://user-images.githubusercontent.com/34922338/107733875-1dfc2b80-6d0d-11eb-9a3f-4eb1201ecd1b.png)

**Comment by iamppz** [comment]
Try to add an order field to every node and validate it in the connect event.
For drag and drop, I think you can listen keyup event on the chart component and call `add` method when it is fired.

**Comment by suhakopan** [comment]
I used a different plugin for drag and drop and got it done, thanks
