### ISSUE TITLE
How can I make arrow bidirectional in connections?

### ISSUE THREAD

**Issue by iamrsojitra** [joyceworks/flowchart-vue#28]
I want to make a connection in both directions which means a connection that has an arrow at both endpoints.

Can you please guide me on how can I achieve this?

**Comment by iamppz** [comment]
Bidirection arrow is not supported, maybe you can do it like this :P
```
connections: [
  {
    source: {id: 1, position: 'right'},
    destination: {id: 2, position: 'left'},
    id: 1,
    type: 'pass',
  },
  {
    source: {id: 2, position: 'left'},
    destination: {id: 1, position: 'right'},
    id: 2,
    type: 'pass',
  },
],

```

**Comment by iamrsojitra** [comment]
@iamppz Yes that I know but it creates two connections and I want a single connection with arrows at both ends.
