### ISSUE TITLE
求求了，把文档写清楚点。完全不知道有些字段的参数怎么填 比如 approvers   

### ISSUE THREAD

**Issue by dlfld** [joyceworks/flowchart-vue#30]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iamppz** [comment]
https://github.com/joyceworks/flowchart-vue/wiki
如有缺失请随时指出，感谢
