### ISSUE TITLE
Small typo in example in README.md

### ISSUE THREAD

**Issue by Joe118** [joyceworks/flowchart-vue#4]
**Describe the bug**
A small typo in 

**To Reproduce**
1. Read README.md:

      handleChartSave(nodes, connections) {
        // axios.post(url, {nodes, **connection**}).then(resp => {  // <===============
        //   this.nodes = resp.nodes;
        //   this.connections = resp.connections;
        //   // Flowchart will refresh after this.nodes and this.connections changed
        // });

**Expected behavior**
1. Should be:

      handleChartSave(nodes, connections) {
        // axios.post(url, {nodes, **connections**}).then(resp => {  // <===============
        //   this.nodes = resp.nodes;
        //   this.connections = resp.connections;
        //   // Flowchart will refresh after this.nodes and this.connections changed
        // });

**Comment by iamppz** [comment]
Fixed 😄
