### ISSUE TITLE
In place edit for a node on flow chart

### ISSUE THREAD

**Issue by Shilpa-K07** [joyceworks/flowchart-vue#40]
**Can we provide in place edit for a node on the flow chart ? Something like, when double click happens on a rect, it should provide an in place text edit field instead of popup.**

Thanks

**Comment by iamppz** [comment]
You can append a hidden input with absolute position to the page, and show it on double click:
```vue
<input @keyup="handleKeyUp" :style="{ position: absolute, x: style.x, y: style.y, display: style.display }" />
```
``` javascript
function handleDblClick(node) {
  this.style = {
    x: node.x + padding,
    y: node.y + padding,
    display: 'block'
  }
}

function handleKeyUp() {
  // update data and hide input if Enter pressed
}
```
