### ISSUE TITLE
Complex custom node

### ISSUE THREAD

**Issue by sigaev-pro** [joyceworks/flowchart-vue#41]
I'm looking for something like your project to build a conversational bot builder for Telegram Messanger. The library you developing is very nice for me.

Please tell me еру way, how I can create more complex custom nodes like described in the attached image.

Here I show a simple message with three inline buttons. A button can be connected only to one message, but the message can be triggered by any number of buttons from other messages.

![image](https://user-images.githubusercontent.com/285154/138609456-751f68e2-82b8-4e7f-80c7-40c2af7ee666.png)

**Comment by iamppz** [comment]
I'm sorry that this component can not satisfy you requirements, but maybe you can fork it and make some changes:
1. Check connector's position and cancel its [mousedown](https://github.com/joyceworks/flowchart-vue/blob/d0e92a792d0a82aa3339c384d92ab96c9491d813/src/components/flowchart/Flowchart.vue#L527)/[mouseup](https://github.com/joyceworks/flowchart-vue/blob/d0e92a792d0a82aa3339c384d92ab96c9491d813/src/components/flowchart/Flowchart.vue#L535) event;
2. Use render function to create a custom Node with a description field and 3 buttons like [this](https://github.com/joyceworks/flowchart-vue/blob/d0e92a792d0a82aa3339c384d92ab96c9491d813/src/views/App.vue#L41):
``` vue
  <flowchart
    :render="render"
  >
```
