### ISSUE TITLE
I want clone the node kinldy can you please help me

### ISSUE THREAD

**Issue by SunnnyGohil** [joyceworks/flowchart-vue#64]
hello I want to clone the node for example 

I select the node then click on clone button so it will clone the another node for me 

thanks in advance

**Comment by mrzygood** [comment]
If I understand you properly a solution is quite easy.
You have your component which is wrapper for flowchart and it passes configuration of nodes and connections.
So you can listen to the event named 'select'. Then you create new object of node with the same data what selected node has currently. Then you add this object to the list of nodes. Flowchart render new view with cloned node.

**Comment by SunnnyGohil** [comment]
@mrzygood is it possible to share Example?

**Comment by mrzygood** [comment]
> @mrzygood is it possible to share Example?

Maybe I will find time tomorrow.

**Comment by SunnnyGohil** [comment]
will be waiting

**Comment by SunnnyGohil** [comment]
> If I understand you properly a solution is quite easy. You have your component which is wrapper for flowchart and it passes configuration of nodes and connections. So you can listen to the event named 'select'. Then you create new object of node with the same data what selected node has currently. Then you add this object to the list of nodes. Flowchart render new view with cloned node.

@mrzygood I want to do below things

1st step : select Node
2nd Step : click on clone button where call clone(node) method 
3rd step : clone(node) method will clone the node and append to nodes properties

**Comment by mrzygood** [comment]
> > If I understand you properly a solution is quite easy. You have your component which is wrapper for flowchart and it passes configuration of nodes and connections. So you can listen to the event named 'select'. Then you create new object of node with the same data what selected node has currently. Then you add this object to the list of nodes. Flowchart render new view with cloned node.
> 
> @mrzygood I want to do below things
> 
> 1st step : select Node 2nd Step : click on clone button where call clone(node) method 3rd step : clone(node) method will clone the node and append to nodes properties

Here you can find really basic example:
https://github.com/mrzygood/flowchart-vue/blob/mm/example-1/src/views/App.vue

**Comment by SunnnyGohil** [comment]
@mrzygood  thank you

I closed the issue
