### ISSUE TITLE
Generic data field for nodes

### ISSUE THREAD

**Issue by rgr** [joyceworks/flowchart-vue#7]
Hey Joyce,

great work! I've check quiet a lot of flowchart libraries and yours is the closest to my needs. 

One thing that would really help me would be to have a generic data field in each node where I could put whatever I want (title in another language, content, etc.) and that doesn't necessarily need to be displayed on the screen. It could be edited on a sidebar on a click event on the node for example. 

That would be really helpful, I hope you can build it :)

**Comment by iamppz** [comment]
You can pass any fields to node, for example:

**Comment by iamppz** [comment]
You can add any field to node, here is an [example](https://codesandbox.io/s/pedantic-rain-9o2ti?file=/src/App.vue).

**Comment by rgr** [comment]
great ! Thanks for the tip :)
