### ISSUE TITLE
Add element to g

### ISSUE THREAD

**Issue by Leshkens** [joyceworks/flowchart-vue#80]
How do I add a new item to the root group of a node? I haven't found how to do this in recent versions.
![image](https://user-images.githubusercontent.com/8939383/208075079-a0a1236c-9c52-4cc8-8f6d-35b04694dfe4.png)

**Comment by mrzygood** [comment]
I am not sure if it helps you, but component prop named `nodes` define what is displayed as nodes groups. So you can pass there array of nodes which should be rendered.

From readme file:
![image](https://user-images.githubusercontent.com/25685729/208089569-62b1135f-a5da-4aac-927e-94009cc640bd.png)
